name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Percy Test
        run: npx @percy/cli exec -- npm run cypress  # or any directory such as public/
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}